services:
    db:
        image: postgres:15
        container_name: db
        restart: always
        env_file:
            - .env
        volumes:
            - postgres-data:/var/lib/postgresql/data

    checkout:
        container_name: checkout
        build:
            context: ./checkout
        env_file: .env
        ports:
            - 1233:80
        depends_on:
            - db

    product-catalog:
        container_name: product-catalog
        build:
            context: ./product-catalog
        env_file: .env
        ports:
            - 1232:80
        depends_on:
            - db

    api:
        container_name: api
        build:
            context: ./api
        env_file:
            - .env
        ports:
            - 1231:80
        depends_on:
            - db

    next-frontend:
        container_name: next-frontend
        build:
            context: ./next-frontend
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - 80:3000
        depends_on:
            - api

volumes:
    postgres-data:
