services:
    db:
        image: postgres
        container_name: db
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER:?database user not set}
            POSTGRES_DB: ${POSTGRES_DB:?database name not set}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?database password not set}
        volumes:
            - postgres-data:/var/lib/postgresql/data

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080

    api:
        container_name: api-prod
        build:
            context: ./api
        ports:
            - 1234:1234
        depends_on:
            - db

    api-dev:
        container_name: api-dev
        build:
            context: ./api
            dockerfile: Dockerfile-dev
        ports:
            - 1235:1235
        depends_on:
            - db

volumes:
    postgres-data:
