services:
    db:
        image: postgres:15
        container_name: db
        restart: always
        env_file:
            - .env-dev
        volumes:
            - postgres-data:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        container_name: adminer
        restart: always
        ports:
            - 8080:8080

    db-filler:
        container_name: db-filler
        env_file:
            - .env-dev
        build:
            context: ./dbscripts
        depends_on:
            - db

    checkout-dev:
        container_name: checkout-dev
        build:
            context: ./checkout
            dockerfile: Dockerfile-dev
        env_file:
            - .env-dev
        ports:
            - 2240:2240
        depends_on:
            - db
            - db-filler

    product-catalog-dev:
        container_name: product-container-dev
        build:
            context: ./product-catalog
            dockerfile: Dockerfile-dev
        env_file:
            - .env-dev
        ports:
            - 2235:2235
        depends_on:
            - db
            - db-filler

    api-dev:
        container_name: api-dev
        build:
            context: ./api
            dockerfile: Dockerfile-dev
        env_file:
            - .env-dev
        ports:
            - 2234:2234
        depends_on:
            - db
            - db-filler

    frontend-dev:
        container_name: frontend-dev
        image: frontend-dev-image
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/frontend
            - node_modules:/frontend/node_modules/
        ports:
            - "2236:3000"
        environment:
            - NODE_ENV=development
            - WATCHPACK_POLLING=true
            - CHOKIDAR_USEPOLLING=true

volumes:
    postgres-data:
    node_modules:
