services:
    db:
        image: postgres:15
        container_name: db
        restart: always
        env_file:
            - .env
        volumes:
            - postgres-data:/var/lib/postgresql/data

    checkout:
        container_name: checkout
        build:
            context: ./checkout
        env_file: .env
        ports:
            - 1240:1240
        depends_on:
            - db

    product-catalog:
        container_name: product-catalog
        build:
            context: ./product-catalog
        env_file: .env
        ports:
            - 1235:1235
        depends_on:
            - db

    api:
        container_name: api
        build:
            context: ./api
        env_file:
            - .env
        ports:
            - 1234:1234
        depends_on:
            - db

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/frontend
            - node_modules:/frontend/node_modules/
        ports:
            - "1236:3000"
        environment:
            - NODE_ENV=development

volumes:
    postgres-data:
    node_modules:
