services:
    db:
        image: postgres:latest
        container_name: db
        restart: always
        env_file:
            - .env-dev
        volumes:
            - postgres-data:/var/lib/postgresql/data

    adminer:
        image: adminer:latest
        container_name: adminer
        restart: always
        ports:
            - 8080:8080

    db-filler:
        container_name: db-filler
        env_file:
            - .env-dev
        build:
            context: ./dbscripts
        depends_on:
            - db

    api-dev:
        container_name: api-dev
        build:
            context: ./api
            dockerfile: Dockerfile-dev
        env_file:
            - .env-dev
        ports:
            - 1235:1235
        depends_on:
            - db
            - db-filler

volumes:
    postgres-data:
