services:
    db:
        image: postgres:latest
        container_name: db
        restart: always
        env_file:
            - .env
        volumes:
            - postgres-data:/var/lib/postgresql/data

    api:
        container_name: api
        build:
            context: ./api
        env_file:
            - .env
        ports:
            - 1234:1234
        depends_on:
            - db

volumes:
    postgres-data:
