def get_structural_queries():
    return (
        """
        DROP TABLE IF EXISTS products;
        """,
        """
        CREATE TABLE products (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            producer TEXT NOT NULL,
            price INTEGER NOT NULL,
            expiry_date	DATE NULL
        );
        """
    )

def get_insert_queries():
    return (
        """
        INSERT INTO products (name, producer, price, expiry_date) 
        VALUES ('Moisturizer', 'l''Oreal', 59, '2023-07-31');
        """,
        """
        INSERT INTO products (name, producer, price, expiry_date) 
        VALUES ('Primer', 'Glam21', 39, '2023-08-19');
        """,
        """
        INSERT INTO products (name, producer, price, expiry_date) 
        VALUES ('Foundation', 'Maybelline', 29, '2023-05-30');
        """,
        """
        INSERT INTO products (name, producer, price) 
        VALUES ('Concealer', 'Maybelline', 34);
        """,
        """
        INSERT INTO products (name, producer, price, expiry_date) 
        VALUES ('Face powder', 'Lakme', 27, '2023-06-30');
        """,
        """
        INSERT INTO products (name, producer, price, expiry_date) 
        VALUES ('Blush', 'Revlon', 42, '2023-07-12');
        """,
        """
        INSERT INTO products (name, producer, price, expiry_date) 
        VALUES ('Lipstick', 'l''Oreal', 26, '2024-02-09');
        """,
        """
        INSERT INTO products (name, producer, price, expiry_date) 
        VALUES ('Lip balm', 'Nivea', 14, '2023-10-30');
        """,
        """
        INSERT INTO products (name, producer, price, expiry_date) 
        VALUES ('Lip gloss', 'Sugar', 21, '2023-12-31');
        """,
        """
        INSERT INTO products (name, producer, price, expiry_date) 
        VALUES ('Mascara', 'Maybelline', 45, '2025-02-28');
        """,
        """
        INSERT INTO products (name, producer, price, expiry_date) 
        VALUES ('CC Cream', 'Lakme', 34, '2023-11-18');
        """,
        """
        INSERT INTO products (name, producer, price, expiry_date) 
        VALUES ('Highlighter', 'Revolution', 67, '2023-09-03');
        """,
        """
        INSERT INTO products (name, producer, price, expiry_date) 
        VALUES ('Setting Spray', 'Nyx', 38, '2023-10-02');
        """,
        """
        INSERT INTO products (name, producer, price, expiry_date) 
        VALUES ('Eye shadow', 'Maybelline', 83, '2022-03-13');
        """
    )

def get_select_queries():
    return (
        """
        SELECT * from products;
        """,
    )