# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:6.0 as build-and-run
WORKDIR /src
COPY src/*.csproj .
RUN dotnet restore
COPY src .
ENV ASPNETCORE_URLS=http://+:2235
ENV ASPNETCORE_ENVIRONMENT=Development
EXPOSE 2235
RUN dotnet build product-catalog.csproj -c Release -o /app
WORKDIR /app
ENTRYPOINT ["dotnet", "product-catalog.dll"]