# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build-dev
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Print variables
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      run: |
        echo $POSTGRES_USER
#     - name: Build image
#       uses: isbang/compose-action@v1.4.1
#       env: 
#         POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#         POSTGRES_PASSOWRD: ${{ secrets.POSTGRES_PASSWORD }}
#       with:
#         compose-file: "./docker-compose.yml"
      
    - name: Check running containers
      run: docker ps -a
