# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build-dev
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create env file
      run: |
          touch .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          cat .env
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Build image
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.yml"
      
    - name: Check running containers
      run: docker ps -a
